name: Multiplayer chess gh page deploy

concurrency:
  group: mp-chess-fe-gh-pages-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    paths:
      - "src/**"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache-dependency-path: |
            package-lock.json
          registry-url: "https://registry.npmjs.org"

      - name: Load FE node_modules cache
        uses: actions/cache@v2
        id: mp-fe-cache
        with:
          path: |
            node_modules
          key: mp-fe-cache-${{ hashFiles('package-lock.json') }}
          restore-keys: mp-fe-cache-

      - name: Install FE node_modules
        if: steps.mp-fe-cache.outputs.cache-hit != 'true'
        id: install
        run: npm ci

      - name: Build
        id: install
        run: npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build #
