name: gh page deploy

concurrency:
  group: mp-chess-fe-gh-pages-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    paths:
      - "client/src/**"
  workflow_dispatch:

defaults:
  run:
    working-directory: client

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: client/package-lock.json
      - run: npm ci
      - run: REACT_APP_ENVIRONMENT="GH" PUBLIC_URL="https://darrenjaworski.github.io/multiplayer-chess/" npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: client/build #
