name: server tests

concurrency:
  group: fe-tests-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    paths:
      - "server/src/**"
  workflow_dispatch:

defaults:
  run:
    working-directory: server

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: server/package-lock.json
      - run: npm ci
      - run: npm test
